name: jivvi
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^16.2.1
  provider: ^6.1.1
  shimmer: ^3.0.0
  google_fonts: ^6.3.1
  image_picker: ^1.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.2
  iconsax: ^0.0.8
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mockito: ^5.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/icons/
