name: social_media_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^16.2.1
  provider: ^6.1.1
  shimmer: ^3.0.0
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  google_fonts: ^6.3.1
  image_picker: ^1.2.0
  firebase_storage: ^13.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mockito: ^5.5.1
  firebase_auth_platform_interface: ^8.1.1
  firebase_auth_mocks: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
