// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTfXsfPZjYLomPfrMUTKxuGGIJCM4ropw',
    appId: '1:400583386990:web:c17ffda9f826e8452a037f',
    messagingSenderId: '400583386990',
    projectId: 'social-media-app-mvp',
    authDomain: 'social-media-app-mvp.firebaseapp.com',
    storageBucket: 'social-media-app-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9eSLsNAmNdrCJmJevR43XBjl_eM8-EKo',
    appId: '1:400583386990:android:af45575ba396a8fc2a037f',
    messagingSenderId: '400583386990',
    projectId: 'social-media-app-mvp',
    storageBucket: 'social-media-app-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpoj5TYkf1BjdG_uSZgpPmhwQSx6KcHYs',
    appId: '1:400583386990:ios:9a921431935636032a037f',
    messagingSenderId: '400583386990',
    projectId: 'social-media-app-mvp',
    storageBucket: 'social-media-app-mvp.firebasestorage.app',
    iosBundleId: 'com.example.social-app',
  );
}
